export enum BookingType {
  HOTEL = 'HOTEL',
  TOUR = 'TOUR',
  CAB = 'CAB',
  HOME_SERVICE = 'HOME_SERVICE',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}
