export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
}

export enum NotificationType {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_ASSIGNED = 'BOOKING_ASSIGNED',
  BOOKING_STATUS = 'BOOKING_STATUS',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYOUT_PAID = 'PAYOUT_PAID',
  SYSTEM = 'SYSTEM',
}
