const LABELS: Record<string, string> = {
  businessName: "Business name",
  operatorName: "Operator name",
  companyName: "Company name",
  manufacturingYear: "Manufacturing year",
  dateOfBirth: "Date of birth",
  drivingLicenceNumber: "Driving licence number",
  vehicleMake: "Vehicle make",
  kitchenName: "Kitchen name",
  foodTypes: "Food types",
  beautyServices: "Beauty services",
  cleaningItems: "Cleaning",
  products: "Items",
  productType: "Items",
  shopCategory: "Shop type",
  serviceLocations: "Service locations",
  loadCapacity: "Load capacity",
  ownerSame: "Owner drives",
  routeType: "Route type",
  loadType: "Load type",
  moveType: "Move type",
  cuisineType: "Cuisine",
  kitchenType: "Kitchen type",
  capacity: "Capacity",
  ownerName: "Owner name",
  email: "Email",
  phone: "Phone",
  houseNumber: "Door number",
  street: "Street",
  address: "Address",
  city: "City",
  area: "Area",
  state: "State",
  location: "Location",
  sectors: "Sectors",
  servicesOffered: "Services",
  experienceYears: "Years of experience",
  description: "Additional information",
  price: "Price",
  priceFrom: "Starting price",
  feeFrom: "Starting fee",
  entryPrice: "Entry price",
  visitCharge: "Visit charge",
  perKm: "Rate per km",
  priceUnit: "Price unit",
  mobileNumber: "Phone",
  shopName: "Shop name",
  serviceName: "Service name",
  packageName: "Package",
  destinations: "Destinations",
  duration: "Duration",
  groupSize: "Group size",
  inclusions: "Inclusions",
  packagePricing: "Package pricing",
  travelType: "Travel type",
  transportOptions: "Transport options",
  pickupPoint: "Pickup point",
  dropPoint: "Drop point",
  food: "Food",
  tripDuration: "Trip duration",
  advancePayment: "Advance payment",
  availableFrom: "Available from",
  availableUntil: "Available until",
  driverName: "Driver name",
  driverMobile: "Driver mobile",
  providerType: "Provider type",
  whatsapp: "WhatsApp",
  vehicleFares: "Vehicle fares",
  vehicleFeatures: "Vehicle features",
  minKm: "Minimum KM",
  minHours: "Minimum hours",
  extraKmCharge: "Extra KM charge",
  waitingCharge: "Waiting charge",
  nightCharge: "Night charge",
  driverAllowance: "Driver allowance",
  cabType: "Cab type",
  vehicleType: "Vehicle type",
  vehicleModel: "Vehicle",
  vehicleNumber: "Vehicle number",
  vehicleTypes: "Vehicles",
  seats: "Seating capacity",
  bookingType: "Booking type",
  licenseNumber: "Driving licence",
  stayKind: "Stay type",
  hostOnProperty: "Host on property",
  meals: "Meals",
  houseRules: "House rules",
  maxGuests: "Max guests",
  hotelName: "Hotel name",
  hotelType: "Hotel type",
  starCategory: "Star category",
  checkPolicy: "Check-in / check-out",
  roomRates: "Room rates",
  roomFeatures: "Room features",
  facilities: "Facilities",
  extraGuestCharge: "Extra guest charge",
  childPolicy: "Child policy",
  booking24x7: "24x7 booking",
  cancellation: "Cancellation",
  roomType: "Room type",
  checkInTime: "Check-in",
  checkOutTime: "Check-out",
  electricianName: "Electrician name",
  customerType: "Customer type",
  emergency: "Emergency service",
  availableDays: "Available days",
  availableTime: "Available time",
  district: "District",
  mandals: "Mandals",
  coverageType: "Service coverage",
  plumberName: "Plumber name",
  hourlyCharge: "Hourly charge",
  fullDayCharge: "Full day charge",
  teamSize: "Team size",
  technicianName: "Technician name",
  carpenterName: "Carpenter name",
  tools: "Tools",
  materialResponsibility: "Material responsibility",
  painterName: "Painter name",
  paintTypes: "Paint types",
  cleanerName: "Name",
  propertyType: "Property type",
  startingCharge: "Starting charge",
  beauticianName: "Name",
  servicePricing: "Service pricing",
  openingTime: "Opening time",
  closingTime: "Closing time",
  serviceFor: "Service for",
  serviceType: "Service type",
  workType: "Work type",
  specialization: "Specialization",
  coverage: "Coverage",
  acType: "AC type",
  applianceType: "Appliances",
  serviceMode: "Service mode",
  spareParts: "Spare parts",
  serviceArea: "Service area",
  serviceKm: "Service area KM",
  gender: "Gender",
  brand: "Brand",
  suitableFor: "Suitable for",
  bookingMode: "Booking mode",
  advanceNotice: "Advance notice",
  listedBy: "Listed by",
};

export function listingFieldLabel(category: string, key: string) {
  if (category === "hotels" && (key === "hotelName" || key === "shopName")) return "Hotel name";
  if (category === "homestay" && (key === "hotelName" || key === "shopName")) return "Homestay name";
  if (category === "tours" && key === "shopName") return "Agency name";
  if (category === "cabs" && key === "shopName") return "Cab service name";
  return LABELS[key] ?? key.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase());
}

export function editableListingFields(category: string, values: Record<string, string>) {
  const hidden = new Set(["listedBy", "latitude", "longitude"]);
  const hasHotelName = Boolean(values.hotelName?.trim());
  const preferred = ["hotelName", "shopName", "businessName", "serviceName", "companyName", "kitchenName", "packageName", "beauticianName", "cleanerName"];
  return Object.entries(values)
    .filter(([key]) => {
      if (hidden.has(key)) return false;
      if ((category === "hotels" || category === "homestay") && key === "shopName" && hasHotelName) return false;
      if (category === "cabs" && (key === "businessName" || key === "serviceName") && values.shopName?.trim()) return false;
      return true;
    })
    .sort(([left], [right]) => {
      const leftRank = preferred.indexOf(left);
      const rightRank = preferred.indexOf(right);
      if (leftRank === -1 && rightRank === -1) return 0;
      if (leftRank === -1) return 1;
      if (rightRank === -1) return -1;
      return leftRank - rightRank;
    });
}
